services:
  quizzer:
    build: .
    container_name: quizzer
    restart: always
    ports:
      - "8006:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./data:/app/data
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_webgateway"
      - "traefik.http.routers.quizzer.rule=Host(`quizzer.home.local`)"
      - "traefik.http.routers.quizzer.entrypoints=web"
      - "traefik.http.services.quizzer.loadbalancer.server.port=3000"
    networks:
      - traefik_webgateway

networks:
  traefik_webgateway:
    external: true
